@BlogPost.API_HostAddress = https://localhost:7008

GET {{BlogPost.API_HostAddress}}/api/blogcategory

###


POST {{BlogPost.API_HostAddress}}/api/blogcategory
Content-Type: application/json

{
  "Name":"J",
  "UrlHandle":"https//kkk",
  "Description":"yeyeyye"
}

###

POST {{BlogPost.API_HostAddress}}/api/blogcategory
Content-Type: application/json

{
  "name": "Hardwares",
  "urlHandle": "https//ss",
  "description": "Hardwares"
}



GET {{BlogPost.API_HostAddress}}/api/blogcategory

###

GET {{BlogPost.API_HostAddress}}/api/blogcategory

###
