// <auto-generated />
using System;
using BlogPostSystem;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogPost.API.Migrations
{
    [DbContext(typeof(BlogPostDbContext))]
    [Migration("20250426114636_Adding BlogPostImage Domain Model")]
    partial class AddingBlogPostImageDomainModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlogCategoryBlogPostT", b =>
                {
                    b.Property<Guid>("BlogPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BlogPostId", "CategoriesId");

                    b.HasIndex("CategoriesId");

                    b.ToTable("BlogCategoryBlogPostT");
                });

            modelBuilder.Entity("BlogPost.API.Model.Domain.BlogCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlHandle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BlogCategory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d3a60d5f-0f35-432f-b250-813c55a7e4f2"),
                            Description = "Latest tech trends and news",
                            Name = "Technology",
                            UrlHandle = "technology"
                        },
                        new
                        {
                            Id = new Guid("6be363c8-0626-4ae8-b617-fe1b2d268503"),
                            Description = "Health, wellness, and daily life tips",
                            Name = "Lifestyle",
                            UrlHandle = "lifestyle"
                        },
                        new
                        {
                            Id = new Guid("922ad5ce-5f9e-4aec-8f99-49c073f8c27b"),
                            Description = "Money management and investment advice",
                            Name = "Finance",
                            UrlHandle = "finance"
                        });
                });

            modelBuilder.Entity("BlogPost.API.Model.Domain.BlogImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BlogImage");
                });

            modelBuilder.Entity("BlogPost.API.Model.Domain.BlogPostT", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeatureImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlHandle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("BlogPostT");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1698f11-114b-42c5-930d-8a4c179090ee"),
                            AuthorName = "John Doe",
                            CategoryId = new Guid("d3a60d5f-0f35-432f-b250-813c55a7e4f2"),
                            Content = "AI is evolving rapidly...",
                            CreatedAt = new DateTime(2025, 4, 26, 11, 46, 36, 61, DateTimeKind.Utc).AddTicks(313),
                            FeatureImageUrl = "ai.jpg",
                            IsPublished = true,
                            IsVisible = true,
                            PublishedDate = new DateTime(2025, 4, 26, 11, 46, 36, 61, DateTimeKind.Utc).AddTicks(303),
                            ShortDescription = "Exploring AI advancements",
                            Title = "The Future of AI",
                            UrlHandle = "future-of-ai"
                        },
                        new
                        {
                            Id = new Guid("16f37fe1-f1c4-4e6f-b4d8-1d485d998d20"),
                            AuthorName = "Jane Smith",
                            CategoryId = new Guid("6be363c8-0626-4ae8-b617-fe1b2d268503"),
                            Content = "Here are some productivity hacks...",
                            CreatedAt = new DateTime(2025, 4, 26, 11, 46, 36, 61, DateTimeKind.Utc).AddTicks(320),
                            FeatureImageUrl = "productivity.jpg",
                            IsPublished = true,
                            IsVisible = true,
                            PublishedDate = new DateTime(2025, 4, 26, 11, 46, 36, 61, DateTimeKind.Utc).AddTicks(319),
                            ShortDescription = "Increase your efficiency",
                            Title = "Best Productivity Hacks",
                            UrlHandle = "best-productivity-hacks"
                        },
                        new
                        {
                            Id = new Guid("916e4e61-4646-455a-aa80-6000fd3832d0"),
                            AuthorName = "Mark Brown",
                            CategoryId = new Guid("922ad5ce-5f9e-4aec-8f99-49c073f8c27b"),
                            Content = "Managing your finances is important...",
                            CreatedAt = new DateTime(2025, 4, 26, 11, 46, 36, 61, DateTimeKind.Utc).AddTicks(336),
                            FeatureImageUrl = "finance.jpg",
                            IsPublished = true,
                            IsVisible = true,
                            PublishedDate = new DateTime(2025, 4, 26, 11, 46, 36, 61, DateTimeKind.Utc).AddTicks(335),
                            ShortDescription = "Smart saving tips",
                            Title = "How to Save Money",
                            UrlHandle = "how-to-save-money"
                        });
                });

            modelBuilder.Entity("BlogPost.API.Model.Domain.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("BlogPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BlogPostId");

                    b.ToTable("Comment");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fcd7c343-dcd1-4af6-8331-82b853455d1d"),
                            AuthorName = "Alice",
                            BlogPostId = new Guid("c1698f11-114b-42c5-930d-8a4c179090ee"),
                            Content = "Great insights on AI!",
                            CreatedAt = new DateTime(2025, 4, 26, 11, 46, 36, 61, DateTimeKind.Utc).AddTicks(370)
                        },
                        new
                        {
                            Id = new Guid("ba986f63-6622-4fd7-bb63-9af75ae415ef"),
                            AuthorName = "Bob",
                            BlogPostId = new Guid("16f37fe1-f1c4-4e6f-b4d8-1d485d998d20"),
                            Content = "These hacks really helped!",
                            CreatedAt = new DateTime(2025, 4, 26, 11, 46, 36, 61, DateTimeKind.Utc).AddTicks(374)
                        },
                        new
                        {
                            Id = new Guid("096e061f-3b01-40ca-861e-2747139c0d89"),
                            AuthorName = "Charlie",
                            BlogPostId = new Guid("916e4e61-4646-455a-aa80-6000fd3832d0"),
                            Content = "Thanks for the tips!",
                            CreatedAt = new DateTime(2025, 4, 26, 11, 46, 36, 61, DateTimeKind.Utc).AddTicks(378)
                        });
                });

            modelBuilder.Entity("BlogCategoryBlogPostT", b =>
                {
                    b.HasOne("BlogPost.API.Model.Domain.BlogPostT", null)
                        .WithMany()
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogPost.API.Model.Domain.BlogCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlogPost.API.Model.Domain.BlogPostT", b =>
                {
                    b.HasOne("BlogPost.API.Model.Domain.BlogCategory", "Category")
                        .WithMany("BlogPosts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BlogPost.API.Model.Domain.Comment", b =>
                {
                    b.HasOne("BlogPost.API.Model.Domain.BlogPostT", "BlogPost")
                        .WithMany("Comments")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BlogPost");
                });

            modelBuilder.Entity("BlogPost.API.Model.Domain.BlogCategory", b =>
                {
                    b.Navigation("BlogPosts");
                });

            modelBuilder.Entity("BlogPost.API.Model.Domain.BlogPostT", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
