// <auto-generated />
using System;
using BlogPostSystem;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogPost.API.Migrations
{
    [DbContext(typeof(BlogPostDbContext))]
    [Migration("20250415141951_AddBlogPostCategoryManyToMany")]
    partial class AddBlogPostCategoryManyToMany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlogCategoryBlogPostT", b =>
                {
                    b.Property<Guid>("BlogPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BlogPostId", "CategoriesId");

                    b.HasIndex("CategoriesId");

                    b.ToTable("BlogCategoryBlogPostT");
                });

            modelBuilder.Entity("BlogPost.API.Model.Domain.BlogCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlHandle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BlogCategory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2f9426f-9e29-48a0-96a0-7f74087f08ec"),
                            Description = "Latest tech trends and news",
                            Name = "Technology",
                            UrlHandle = "technology"
                        },
                        new
                        {
                            Id = new Guid("898a4e04-8960-445d-a195-4a1215cae0bc"),
                            Description = "Health, wellness, and daily life tips",
                            Name = "Lifestyle",
                            UrlHandle = "lifestyle"
                        },
                        new
                        {
                            Id = new Guid("5990b514-e978-40dd-b964-9259e657bda7"),
                            Description = "Money management and investment advice",
                            Name = "Finance",
                            UrlHandle = "finance"
                        });
                });

            modelBuilder.Entity("BlogPost.API.Model.Domain.BlogPostT", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeatureImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlHandle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("BlogPostT");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8149d258-31ba-4c3e-bec8-7ebf8712df47"),
                            AuthorName = "John Doe",
                            CategoryId = new Guid("b2f9426f-9e29-48a0-96a0-7f74087f08ec"),
                            Content = "AI is evolving rapidly...",
                            CreatedAt = new DateTime(2025, 4, 15, 14, 19, 50, 575, DateTimeKind.Utc).AddTicks(6859),
                            FeatureImageUrl = "ai.jpg",
                            IsPublished = true,
                            IsVisible = true,
                            PublishedDate = new DateTime(2025, 4, 15, 14, 19, 50, 575, DateTimeKind.Utc).AddTicks(6853),
                            ShortDescription = "Exploring AI advancements",
                            Title = "The Future of AI",
                            UrlHandle = "future-of-ai"
                        },
                        new
                        {
                            Id = new Guid("ea9101e8-4b79-4456-b8c5-aec8adbf670f"),
                            AuthorName = "Jane Smith",
                            CategoryId = new Guid("898a4e04-8960-445d-a195-4a1215cae0bc"),
                            Content = "Here are some productivity hacks...",
                            CreatedAt = new DateTime(2025, 4, 15, 14, 19, 50, 575, DateTimeKind.Utc).AddTicks(6868),
                            FeatureImageUrl = "productivity.jpg",
                            IsPublished = true,
                            IsVisible = true,
                            PublishedDate = new DateTime(2025, 4, 15, 14, 19, 50, 575, DateTimeKind.Utc).AddTicks(6866),
                            ShortDescription = "Increase your efficiency",
                            Title = "Best Productivity Hacks",
                            UrlHandle = "best-productivity-hacks"
                        },
                        new
                        {
                            Id = new Guid("feab0e53-7180-4679-bda6-77ec4999333c"),
                            AuthorName = "Mark Brown",
                            CategoryId = new Guid("5990b514-e978-40dd-b964-9259e657bda7"),
                            Content = "Managing your finances is important...",
                            CreatedAt = new DateTime(2025, 4, 15, 14, 19, 50, 575, DateTimeKind.Utc).AddTicks(6872),
                            FeatureImageUrl = "finance.jpg",
                            IsPublished = true,
                            IsVisible = true,
                            PublishedDate = new DateTime(2025, 4, 15, 14, 19, 50, 575, DateTimeKind.Utc).AddTicks(6871),
                            ShortDescription = "Smart saving tips",
                            Title = "How to Save Money",
                            UrlHandle = "how-to-save-money"
                        });
                });

            modelBuilder.Entity("BlogPost.API.Model.Domain.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("BlogPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BlogPostId");

                    b.ToTable("Comment");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a6354e72-c10e-449f-bca3-d5d82d3d99d2"),
                            AuthorName = "Alice",
                            BlogPostId = new Guid("8149d258-31ba-4c3e-bec8-7ebf8712df47"),
                            Content = "Great insights on AI!",
                            CreatedAt = new DateTime(2025, 4, 15, 14, 19, 50, 575, DateTimeKind.Utc).AddTicks(6910)
                        },
                        new
                        {
                            Id = new Guid("dd3752fd-1b39-409b-89b4-c1c82aad411e"),
                            AuthorName = "Bob",
                            BlogPostId = new Guid("ea9101e8-4b79-4456-b8c5-aec8adbf670f"),
                            Content = "These hacks really helped!",
                            CreatedAt = new DateTime(2025, 4, 15, 14, 19, 50, 575, DateTimeKind.Utc).AddTicks(6915)
                        },
                        new
                        {
                            Id = new Guid("6c3472d4-3f1d-44eb-b191-e4703c1483e5"),
                            AuthorName = "Charlie",
                            BlogPostId = new Guid("feab0e53-7180-4679-bda6-77ec4999333c"),
                            Content = "Thanks for the tips!",
                            CreatedAt = new DateTime(2025, 4, 15, 14, 19, 50, 575, DateTimeKind.Utc).AddTicks(6918)
                        });
                });

            modelBuilder.Entity("BlogCategoryBlogPostT", b =>
                {
                    b.HasOne("BlogPost.API.Model.Domain.BlogPostT", null)
                        .WithMany()
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogPost.API.Model.Domain.BlogCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlogPost.API.Model.Domain.BlogPostT", b =>
                {
                    b.HasOne("BlogPost.API.Model.Domain.BlogCategory", "Category")
                        .WithMany("BlogPosts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BlogPost.API.Model.Domain.Comment", b =>
                {
                    b.HasOne("BlogPost.API.Model.Domain.BlogPostT", "BlogPost")
                        .WithMany("Comments")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BlogPost");
                });

            modelBuilder.Entity("BlogPost.API.Model.Domain.BlogCategory", b =>
                {
                    b.Navigation("BlogPosts");
                });

            modelBuilder.Entity("BlogPost.API.Model.Domain.BlogPostT", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
